joint_names: ['gripper_finger1_joint']

#action_name: /arm_controller/follow_joint_trajectory
action_name: /gripper/joint_trajectory_controller/follow_joint_trajectory
#service_ns: /arm_controller
service_ns: /gripper/driver
default_vel: 0.6

# back side positions
home: [[0.0]]
