controller_list:
  - name: fake_arm_controller
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5
  - name: fake_gripper_controller
    joints:
      - arm_big_finger_left_join
      - arm_big_finger_right_join