controller_list:
  - name: fake_arm_left_controller
    joints:
      - arm_left_1_joint
      - arm_left_2_joint
      - arm_left_3_joint
      - arm_left_4_joint
      - arm_left_5_joint
      - arm_left_6_joint
      - arm_left_7_joint
      - gripper_left_finger_1_joint
      - gripper_left_finger_2_joint
  - name: fake_left_gripper_controller
    joints:
      - gripper_left_finger_1_joint
      - gripper_left_finger_2_joint